#!/bin/bash

# this script loops through all of the specified files in numerical order

readarray -d '' entries < <(printf '%s\0' $1-*.iq | sort -zV)
for i in "${entries[@]}"; do
  echo "-- $i"
  python iqreader.py -v --osr 4 -i $i
done
