#!/usr/bin/python3

# cp files generated by adsb_read into directories arranged by date
# python scripts/cptset.py -s /srv/breamdisk/adsb-data -d /tmp

import pickle
import shutil
import numpy as np
import os
import re
import math
import pyModeS as pms
from ADSBwave import *
import pdb

def mkdircp(src, dstdir, dirname, dryrun=True):
    dstdir = dstdir + '/' + dirname
    if not os.path.isdir(dstdir):
        print('os.mkdir({})'.format(dstdir))
        if not dryrun:
            os.mkdir(dstdir)
    print('cp {} {}\n'.format(src, dstdir))
    print('shutil.copy2(src, dstdir)'.format(src, dstdir)) 
    if not dryrun:
        shutil.copy2(src, dstdir)

# read and decode all .bin files in the directory, 
def readdir(srcdir, dstdir, cargs):
    wave = ADSBwave(osr=cargs.osr, verbose=cargs.verbose)
    fsize = 0
    fcount = 0
    verified = 0
    failed = 0
    dataset = []
    dirfiles = os.listdir(srcdir)
    dirfiles.sort(key=lambda f: int(re.sub('\D', '', f)))
    # dirfiles_sorted = sorted(dirfiles)

    for filename in dirfiles:
        if filename.endswith(".bin"):
            fcount += 1
            fname = (os.path.join(srcdir, filename))
            mtime = os.path.getmtime(fname)
            xctime = time.strftime("%Y-%m-%d", time.localtime(mtime))
            mkdircp(fname, dstdir, '{}'.format(xctime), dryrun=cargs.dryrun)

# call readdir for all subdirectories of rootdir
def dirwalk(rootdir, dstdir, cargs):

    dataset = []
    for dirname in os.listdir(rootdir):
        print('* {}'.format(dirname))
        if os.path.isdir(f"{rootdir}/{dirname}"):
            print(f"reading from: {dirname} in {rootdir}")
            readdir(f"{rootdir}/{dirname}", dstdir, cargs)
    return dataset
                
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0, help='Verbose mode')
    parser.add_argument('-s', '--srcdir', type=str, default='.', help='Root directory where to find the raw adsb data files in .bin format')
    parser.add_argument('-d', '--dstdir', type=str, default='/tmp', help='Root directory where to place the raw adsb data files in .bin format')
    parser.add_argument('--dryrun', action='store_true', default=False, help='Do a dry-run (just create directories.')
    parser.add_argument('--osr', action='store', type=int, default=4, help='Over-Sampling Rate')
    cargs = parser.parse_args()

    dataset = dirwalk(cargs.srcdir, cargs.dstdir, cargs)
    
    exit(0)
    
